repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args:
    - --markdown-linebreak-ext=md
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black
    args:
    - --line-length
    - '79'
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args:
    - --profile
    - black
    - --line-length
    - '79'
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.4
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix
    - --line-length
    - '79'
  - id: ruff-format
    args:
    - --line-length
    - '79'
- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    args:
    - --max-line-length=79
    - --extend-ignore=E203,W503
- repo: local
  hooks:
  - id: devcovenant
    name: enforce repository policies (DevCovenant)
    entry: python3 -m devcovenant.cli check
    language: system
    types:
    - text
    pass_filenames: false
    always_run: true
exclude: |-
  (?x)
  (^|/)
  (
    vendor
    | third_party
    | node_modules
    | \.gha\-pycache
    | \.venv
    | __pycache__
    | \.pytest_cache
    | \.mypy_cache
    | build
    | dist
    | _site
    | site
    | \.git
    | \.python
    | output
    | logs
    | \.ruff_cache
    | \.tox
    | \.nox
    | \.hypothesis
    | \.cache
    | \.venv\.lock
    | [^/]+\.egg-info
  )
  (/|$)
